server:
  port: 8080
spring:
  application:
    #应用的名称
    name: demo
  profiles:
    active: reggie
  datasource:
    url: jdbc:mysql://${demo.mysql.ip}:${demo.mysql.port}/${demo.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${demo.mysql.username}
    password: ${demo.mysql.password}
    driver-class-name: ${demo.mysql.drive}
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
mybatis-plus:
  #指定Mapper映射路径
  ####此配置似乎有问题###
  #mapper-locations: classpath:com/zhao/springboot/mapper/*.xml
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID